# Generated by Django 3.0.5 on 2020-06-01 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import servers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=30)),
                ('color', models.CharField(choices=[('N', 'No color'), ('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow'), ('G', 'Green'), ('L', 'Light blue'), ('B', 'Blue'), ('V', 'Violet')], default='N', max_length=1, verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=servers.models.get_upload_path, verbose_name='picture')),
                ('type_chat', models.CharField(choices=[('D', 'Dialog'), ('C', 'Chat')], default='D', max_length=1, verbose_name='type')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=280, verbose_name='message')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('labels', models.ManyToManyField(to='servers.Label', verbose_name='labels')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server', verbose_name='server')),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
